apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: agent-audit-sink
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      url: "http://10.110.159.250:8765/k8s_audit"
